### ISSUE TITLE
Update epic-spinners landing

### ISSUE THREAD

**Issue by asvae** [epicmaxco/epic-spinners#61]
The problem with epic-spinners landing is that at the moment it's extremely outdated. (you can't even update anything there, most of the dependencies are deprecated)

Right now we have 2 repos:
* https://github.com/epicmaxco/epic-spinners-landing - this is documentation repo - ([docs](https://epic-spinners.epicmax.co/))
* https://github.com/epicmaxco/epic-spinners - this is library itself ([npm](https://www.npmjs.com/package/epic-spinners))

So what we want to do with it:
- [x] Combine both projects to monorepo similar to what we do for vuestic-ui #62
- [x] Update all dependencies (probably starting fresh vite project for docs would be the smart idea, for spinners library - would be great if we can reuse initial build for now, as build process changes could introduce breaking changes or would need significant testing)
- [x] Archive https://github.com/epicmaxco/epic-spinners-landing 
- [ ] Fix #60
